services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_LOGS=error # Change to "warning", "error", or "critical" to reduce verbosity
      - RABBITMQ_SASL_LOGS=error
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 60s

  detector:
    build:
      context: .
      dockerfile: monitor/Dockerfile
    container_name: "monitor"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ORIGENES_AUTORIZADOS="['192.168.0.2']"
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "sleep 10 && echo 'detector ready'"]
      interval: 5s
      retries: 3
      start_period: 2s

